language: node_js
node_js:
    - "0.12"
    - "0.11"
    - "0.10"
    - "iojs"
notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.org#noswap"
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} - %{build_url}"
        use_notice: true
        skip_join: true
