language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
notifications:
  email: false
  irc:
    channels:
    - irc.freenode.org#noswap
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      - %{build_url}'
    use_notice: true
    skip_join: true
deploy:
  provider: releases
  api_key:
    secure: AF8RTvOyPAhG9m2INq+G4ORUiTLCsCHxe5LSBagumiKtK3UJz/rq14TpbUU0ZsT+gYzK+Wt6nLKjvKDzKavHZYV+X27jJY/uYQ5dy0wUGPwxoajEAwqiGlrhCc4lovRMQ56h4aeSJlGFE0AKZsq/E6X8BBP4C2Kcfre2hPBby8A=
  skip_cleanup: true
  file: build/foo.zip
  on:
    repo: jreese/apollo
    tags: true
    node: 'iojs'
